#!/usr/bin/env ruby
#/ Usage: download 
#/ Downloads and decrypts data from the public fuseShift app.
#/
#/ Options:
#/  -u, --url=URL        public fuseShift app's URL
#/  -k, --key=KEY        path to the private key
require 'base64'
require 'csv'
require 'json'
require 'net/http'
require 'openssl'
require 'uri'
require 'optparse'

# default options
remote_url = ENV["FUSE_SHIFT_REMOTE_URL"] || "http://localhost:3000"
key_path = './fuse_shift.private.pem'

# parse arguments
ARGV.options do |opts|
  opts.on("-u", "--url=val") { |val| remote_url = val }
  opts.on("-k", "--key=val") { |val| key_path = val } 
  opts.on_tail("-h", "--help") { exec "grep ^#/<'#{__FILE__}'|cut -c4-" }
  opts.parse!
end


def decrypt(string, key_path)
  rsa_private_key = OpenSSL::PKey::RSA.new(File.read(key_path), "ruby")
  rsa_private_key.private_decrypt(Base64.strict_decode64(string))
end

def ends_with?(value, string)
  value.to_s[-string.length, string.length] == string
end

def get(url)
  uri = URI.parse("#{url}/registrations?confirmed=true")
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = uri.scheme == "https"
  response = http.get(uri.request_uri)
  JSON.parse(response.body)
end

def normalize(data, key_path)
  data.map do |attributes|
    attributes.map do |key, value|
      value = decrypt(value, key_path) if ends_with?(value, "==")
      key, value = "is_friend", value ? 0 : 1 if key == "is_member" 
      key = 'hashed_email' if key == 'hashedEmail'
      [key, value]
    end.to_h
  end
end

def to_csv(data)
  headers = data.first.keys
  csv = CSV.generate(headers: true) do |csv|
    csv << headers
    data.each { |attributes| csv << attributes } 
  end
end
  
data = get(remote_url)
data = normalize(data, key_path)
puts to_csv(data)
  
