mailaccount:
  smtp: "smtp.meineemaildomain.de"
  port: 587
  user: "meinlogin"
  email: "meineemail@meineemaildomain.de"


send_deadline_warning: 
  csv_path: "./config/production/data.csv" #path to csv file with unconfirmed registrations (output of download)
  email_text: 
    registree:
      subject: "Please confirm your email-address for the festival"
      body: |
        Hey, 
        
        the deadline for the festival registration is on 18.9.2019 .
        
        You didn't confirm your email-address for your festival registration yet. Please click on the link in the email you got some time ago.
    contact_person: 
      subject: 'Umconfirmed email-adresses for the festival'
      body: |
        Hey,
        
        the deadline for the festival registration is on 18.9.2019. 
        
        Some of the people you registered didn't confirm their email-address (see below). Make sure there's no typo in the addresses. 
        
        We wrote them an email. If you want to you can also remind them in person.